// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mymonopoly.entity;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.mymonopoly.entity.AppRole;
import net.mymonopoly.entity.AppRoleDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect AppRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppRoleDataOnDemand: @Component;
    
    private Random AppRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<AppRole> AppRoleDataOnDemand.data;
    
    public AppRole AppRoleDataOnDemand.getNewTransientAppRole(int index) {
        AppRole obj = new AppRole();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AppRoleDataOnDemand.setDescription(AppRole obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void AppRoleDataOnDemand.setName(AppRole obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public AppRole AppRoleDataOnDemand.getSpecificAppRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AppRole obj = data.get(index);
        Long id = obj.getId();
        return AppRole.findAppRole(id);
    }
    
    public AppRole AppRoleDataOnDemand.getRandomAppRole() {
        init();
        AppRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AppRole.findAppRole(id);
    }
    
    public boolean AppRoleDataOnDemand.modifyAppRole(AppRole obj) {
        return false;
    }
    
    public void AppRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AppRole.findAppRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AppRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AppRole>();
        for (int i = 0; i < 10; i++) {
            AppRole obj = getNewTransientAppRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
