// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mymonopoly.entity;

import java.util.List;
import net.mymonopoly.entity.GameChest;
import net.mymonopoly.entity.GameChestDataOnDemand;
import net.mymonopoly.entity.GameChestIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GameChestIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GameChestIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GameChestIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GameChestIntegrationTest: @Transactional;
    
    @Autowired
    GameChestDataOnDemand GameChestIntegrationTest.dod;
    
    @Test
    public void GameChestIntegrationTest.testCountGameChests() {
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", dod.getRandomGameChest());
        long count = GameChest.countGameChests();
        Assert.assertTrue("Counter for 'GameChest' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GameChestIntegrationTest.testFindGameChest() {
        GameChest obj = dod.getRandomGameChest();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to provide an identifier", id);
        obj = GameChest.findGameChest(id);
        Assert.assertNotNull("Find method for 'GameChest' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GameChest' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GameChestIntegrationTest.testFindAllGameChests() {
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", dod.getRandomGameChest());
        long count = GameChest.countGameChests();
        Assert.assertTrue("Too expensive to perform a find all test for 'GameChest', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GameChest> result = GameChest.findAllGameChests();
        Assert.assertNotNull("Find all method for 'GameChest' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GameChest' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GameChestIntegrationTest.testFindGameChestEntries() {
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", dod.getRandomGameChest());
        long count = GameChest.countGameChests();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GameChest> result = GameChest.findGameChestEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GameChest' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GameChest' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GameChestIntegrationTest.testFlush() {
        GameChest obj = dod.getRandomGameChest();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to provide an identifier", id);
        obj = GameChest.findGameChest(id);
        Assert.assertNotNull("Find method for 'GameChest' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGameChest(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GameChest' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GameChestIntegrationTest.testMergeUpdate() {
        GameChest obj = dod.getRandomGameChest();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to provide an identifier", id);
        obj = GameChest.findGameChest(id);
        boolean modified =  dod.modifyGameChest(obj);
        Integer currentVersion = obj.getVersion();
        GameChest merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GameChest' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GameChestIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", dod.getRandomGameChest());
        GameChest obj = dod.getNewTransientGameChest(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GameChest' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GameChest' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GameChest' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GameChestIntegrationTest.testRemove() {
        GameChest obj = dod.getRandomGameChest();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameChest' failed to provide an identifier", id);
        obj = GameChest.findGameChest(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GameChest' with identifier '" + id + "'", GameChest.findGameChest(id));
    }
    
}
