// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mymonopoly.entity;

import java.util.List;
import net.mymonopoly.entity.HistoryPlayer;
import net.mymonopoly.entity.HistoryPlayerDataOnDemand;
import net.mymonopoly.entity.HistoryPlayerIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HistoryPlayerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HistoryPlayerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HistoryPlayerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HistoryPlayerIntegrationTest: @Transactional;
    
    @Autowired
    HistoryPlayerDataOnDemand HistoryPlayerIntegrationTest.dod;
    
    @Test
    public void HistoryPlayerIntegrationTest.testCountHistoryPlayers() {
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", dod.getRandomHistoryPlayer());
        long count = HistoryPlayer.countHistoryPlayers();
        Assert.assertTrue("Counter for 'HistoryPlayer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HistoryPlayerIntegrationTest.testFindHistoryPlayer() {
        HistoryPlayer obj = dod.getRandomHistoryPlayer();
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to provide an identifier", id);
        obj = HistoryPlayer.findHistoryPlayer(id);
        Assert.assertNotNull("Find method for 'HistoryPlayer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HistoryPlayer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HistoryPlayerIntegrationTest.testFindAllHistoryPlayers() {
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", dod.getRandomHistoryPlayer());
        long count = HistoryPlayer.countHistoryPlayers();
        Assert.assertTrue("Too expensive to perform a find all test for 'HistoryPlayer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HistoryPlayer> result = HistoryPlayer.findAllHistoryPlayers();
        Assert.assertNotNull("Find all method for 'HistoryPlayer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HistoryPlayer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HistoryPlayerIntegrationTest.testFindHistoryPlayerEntries() {
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", dod.getRandomHistoryPlayer());
        long count = HistoryPlayer.countHistoryPlayers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HistoryPlayer> result = HistoryPlayer.findHistoryPlayerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HistoryPlayer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HistoryPlayer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HistoryPlayerIntegrationTest.testFlush() {
        HistoryPlayer obj = dod.getRandomHistoryPlayer();
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to provide an identifier", id);
        obj = HistoryPlayer.findHistoryPlayer(id);
        Assert.assertNotNull("Find method for 'HistoryPlayer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHistoryPlayer(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'HistoryPlayer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HistoryPlayerIntegrationTest.testMergeUpdate() {
        HistoryPlayer obj = dod.getRandomHistoryPlayer();
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to provide an identifier", id);
        obj = HistoryPlayer.findHistoryPlayer(id);
        boolean modified =  dod.modifyHistoryPlayer(obj);
        Integer currentVersion = obj.getVersion();
        HistoryPlayer merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'HistoryPlayer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HistoryPlayerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to initialize correctly", dod.getRandomHistoryPlayer());
        HistoryPlayer obj = dod.getNewTransientHistoryPlayer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HistoryPlayer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HistoryPlayer' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HistoryPlayer' identifier to no longer be null", obj.getId());
    }
    
}
