// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mymonopoly.entity;

import net.mymonopoly.entity.GameTheme;

privileged aspect GameTheme_Roo_JavaBean {
    
    public String GameTheme.getName() {
        return this.name;
    }
    
    public void GameTheme.setName(String name) {
        this.name = name;
    }
    
}
