// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mymonopoly.entity;

import net.mymonopoly.entity.GameRailroad;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GameRailroad_Roo_Configurable {
    
    declare @type: GameRailroad: @Configurable;
    
}
